name: PrevDNS
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update:
    name: Update blocklist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.13.1

      - name: Run PrevDNS
        env:
          cf-zt-identifier: ${{ secrets.cf-zt-identifier }}
          cf-zt-auth-token: ${{ secrets.cf-zt-auth-token }}
          cf-zt-rule-identity-expression: ${{ secrets.cf-zt-rule-identity-expression }}
        run: deno run --allow-env --allow-net --allow-read ./main.ts
